spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-sources[0]:
            endpoint: https://msajdkv.vault.azure.net/

azure:
  storage:
    connection-string: ${storageAccountConnectionString}
